# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fa1syLKIOdAttnHS0BJc7VaMp5vB-9BQ
"""

class Library:
    def __init__(self, filename='books.txt'):
        self.filename = filename
        self.file = open(self.filename, 'a+')
        self.file.seek(0)

    def __del__(self):
        if self.file:
            self.file.close()

    def load_books(self):
        self.file.seek(0)
        books = [line.strip() for line in self.file]
        return books

    def list_books(self):
        books = self.load_books()
        for book in books:
            name, author, release_date, number_of_pages = book.split(', ')
            print(f"Kitap Adı: {name}, Yazar: {author}")

    def add_book(self):
        title = input("Kitap başlığını girin: ")
        author = input("Yazarın adını girin: ")
        release_year = input("İlk yayın yılını girin: ")
        number_of_pages = input("Sayfa sayısını girin: ")
        self.file.seek(0, 2)
        self.file.write(f"{title}, {author}, {release_year}, {number_of_pages}\n")
        self.file.flush()

    def remove_book(self):
        title_to_remove = input("Silinecek kitabın başlığını girin: ")
        books = self.load_books()
        updated_books = [book for book in books if not book.startswith(title_to_remove)]
        self.file.seek(0)
        self.file.truncate(0)
        for book in updated_books:
            self.file.write(f"{book}\n")
        self.file.flush()


def show_menu(lib):
    while True:
        print("\n*** MENU ***")
        print("1) List Books")
        print("2) Add Book")
        print("3) Remove Book")
        print("4) Exit")
        choice = input("Please select an option (1-4): ")

        if choice == '1':
            print("\nListing all books...\n")
            lib.list_books()
        elif choice == '2':
            print("\nAdding a new book...\n")
            lib.add_book()
        elif choice == '3':
            print("\nRemoving a book...\n")
            lib.remove_book()
        elif choice == '4':
            print("Exiting the program.")
            break
        else:
            print("Invalid input, please try again.")


if __name__ == "__main__":
    lib = Library()
    show_menu(lib)